---
name: icey-prometheus-statsd-exporter
version: 0.0.1
summary: Prometheus statsd Exporter
description: |
  Exporter that exposes information gathered from statsd for use by the Prometheus monitoring system
confinement: strict
grade: stable
base: core18
parts:
  statsd-exporter:
    plugin: go
    source: https://github.com/prometheus/statsd_exporter.git
    go-importpath: github.com/prometheus/statsd_exporter
    # build-packages:
    #   - librados-dev
    #   - libnss3
    #   - libsqlite3-0
    prime:
      - bin/statsd_exporter
  statsd-exporter-config:
    plugin: dump
    source: .
    organize:
      daemon_arguments: etc/statsd_exporter/daemon_arguments.example
      statsd_exporter_wrapper: bin/statsd_exporter.wrapper
    # stage-packages:
    #   - librados2
    #   - libgtk3-nocsd0
    #   - libnss3
    #   - libstdc++6
    prime:
      - etc/statsd_exporter/daemon_arguments.example
      - bin/statsd_exporter.wrapper
      - lib/*
      - usr/lib/*
apps:
  statsd-exporter:
    command: 'bin/statsd_exporter.wrapper'
    plugs: [network-bind]
    daemon: simple
