---
name: icey-prometheus-bird-exporter
version: 0.0.1
summary: Prometheus bird Exporter
description: |
  Exporter that exposes information gathered from bird(2) for use by the Prometheus monitoring system
confinement: classic
grade: stable
base: core20
parts:
  bird-exporter:
    plugin: go
    source: https://github.com/czerwonk/bird_exporter.git
    # go-importpath: github.com/czerwonk/bird_exporter
    # build-packages:
    #   - librados-dev
    #   - libnss3
    #   - libsqlite3-0
    prime:
      - bin/bird_exporter
  bird-exporter-config:
    plugin: dump
    source: .
    organize:
      daemon_arguments: etc/bird_exporter/daemon_arguments.example
      bird_exporter_wrapper: bin/bird_exporter.wrapper
    # stage-packages:
    #   - librados2
    #   - libgtk3-nocsd0
    #   - libnss3
    #   - libstdc++6
    prime:
      - etc/bird_exporter/daemon_arguments.example
      - bin/bird_exporter.wrapper
      - lib/*
      - usr/lib/*
apps:
  bird-exporter:
    command: 'bin/bird_exporter.wrapper'
    plugs:
    - network-bind
    daemon: simple
