#!/bin/sh

# Setup initial config if doesn't exist yet
test -e $SNAP_DATA/daemon_arguments || cp $SNAP/etc/statsd_exporter/daemon_arguments.example $SNAP_DATA/daemon_arguments

. $SNAP_DATA/daemon_arguments
echo "* Running $SNAP/bin/statsd_exporter with args: $ARGS"
export LD_LIBRARY_PATH=$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/statsd
$SNAP/bin/statsd_exporter $ARGS
